Register
notkimroberts/collectors-trading-platform pull request #12
Opened 2020-10-24 23:14 UTC by jhhlim

it works! 

Notes 10-24-2020
- register post w/ forms
and login post commands
-hashes password
-want to consider removing username altogether (we have email already) b/c we are not checking for duplicate username in auth/index.js 
-want to add back cookies later on
-redirection after confirmation of successful sign in and sign up
-validation check passed when logging in (success and unsuccessful - correct err msg provided in svr log)

2020-10-24 23:34 UTC, tomki1 approved these changes
LGTM

2020-10-25 04:38 UTC, notkimroberts commented
@jhhlim I tried to run this branch locally and it does not run. 

```
/Users/kimroberts/code/projects/collectors-trading-platform/sql/users.js:1
onst knex = require('../connection');
     ^^^^

SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:1116:16)
    at Module._compile (internal/modules/cjs/loader.js:1164:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/Users/kimroberts/code/projects/collectors-trading-platform/auth/index.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
```

2020-10-25 04:41 UTC, notkimroberts requested changes

2020-10-25 04:41 UTC, notkimroberts commented on sql/users.js
> +onst knex = require('../connection');
@jhhlim What's the rationale for this file being in `sql`? Since this file is working with users then I think the contents should be merged into the existing `models/collector.js` file since `collector` is our version of a `user` no?

2020-10-25 20:56 UTC, tomki1 commented
@notkimroberts sorry there was a typo. I just fixed it and it works now

2020-10-25 22:04 UTC, jhhlim commented on sql/users.js
> +onst knex = require('../connection');
there's no rationale this was from the tutorial

2020-10-25 22:05 UTC, jhhlim commented on sql/users.js
> +onst knex = require('../connection');
I can't answer these questions. I did not create models/collector.js nor user.js

2020-10-25 22:22 UTC, jhhlim reviewed
updated to removed users.js

2020-10-25 23:35 UTC, notkimroberts approved these changes

2020-10-25 23:36 UTC, merged