added partials, navigation bar, routes
notkimroberts/collectors-trading-platform pull request #3
Opened 2020-10-18 02:33 UTC by tomki1

2020-10-18 03:28 UTC, jhhlim approved these changes

2020-10-18 16:00 UTC, notkimroberts requested changes
@tomki1 There are some minor changes needed to the `.hbs` files. Your code works great but this will reduce code duplication.

2020-10-18 16:00 UTC, notkimroberts commented on views/layout.hbs
>      <body>
@tomki1 Since all of the views have a `{{> header}}` partial. That could just be included above Line 11 in `layout.hbs` and every route will inherit.

2020-10-18 16:00 UTC, notkimroberts commented on views/login.hbs
> +        {{{title}}}
@tomki1 Every route inherits this layout so each page only really needs a `{{{title}}}` tag.

2020-10-18 16:00 UTC, notkimroberts commented on views/profile.hbs
> +        {{{title}}}
@tomki1 Every route inherits this layout so each page only really needs a `{{{title}}}` tag.

2020-10-18 16:00 UTC, notkimroberts commented on views/register.hbs
> +        {{{title}}}
@tomki1 Every route inherits this layout so each page only really needs a `{{{title}}}` tag.

2020-10-18 16:00 UTC, notkimroberts commented on views/rules.hbs
> +        {{{title}}}
@tomki1 Every route inherits this layout so each page only really needs a `{{{title}}}` tag.

2020-10-19 02:30 UTC, notkimroberts approved these changes
LGTM. 👍

2020-10-19 02:32 UTC, merged