Show user collection
notkimroberts/collectors-trading-platform pull request #34
Opened 2020-11-08 05:53 UTC by jhhlim

1. profile.hbs 
    a. has, wants, for trade
    b. inventory, wants, for trade in user profile
    c. submit button at end of the sections
2. profile.js updated to show all collectibles so user will adjust quantities

2020-11-08 15:53 UTC, notkimroberts requested changes

2020-11-08 15:53 UTC, notkimroberts commented on views/profile.hbs
> +      <input type="submit" value="Submit">
@jhhlim `Submit` doesn't appear to be connected to any route so clicking it does not update values.

2020-11-08 15:53 UTC, notkimroberts commented on views/profile.hbs
> +     <input type="submit" value="Submit">
@jhhlim `Submit` doesn't appear to be connected to any route so clicking it does not update values.

2020-11-08 15:53 UTC, notkimroberts commented on views/profile.hbs
> +<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
@jhhlim Fontawesome is included in `layout` so it shouldn't need to be imported here.

2020-11-08 19:52 UTC, tomki1 requested changes
I think you may need an "update" knex query to update the quantities

2020-11-08 19:52 UTC, tomki1 commented on routes/profile.js
> +        // .andWhere('collection.has_quantity', '>', 0);
why is this commented out? we need to grab the collectible data where collector_id is equal to the signed in user. Otherwise, you are grabbing all collectors' data

2020-11-08 19:52 UTC, tomki1 commented on routes/profile.js
> +        // .andWhere('collection.wants_quantity', '>', 0);
why is this commented out? we need to grab the collectible data where collector_id is equal to the signed in user. Otherwise, you are grabbing all collectors' data

2020-11-08 19:52 UTC, tomki1 commented on routes/profile.js
> +        // .andWhere('collection.willing_to_trade_quantity', '>', 0);
why is this commented out? we need to grab the collectible data where collector_id is equal to the signed in user. Otherwise, you are grabbing all collectors' data

2020-11-08 19:58 UTC, jhhlim commented on views/profile.hbs
> +      <input type="submit" value="Submit">
I'm sorry I didn't mention this in PR. 

I have only done the look and feel yet, I have not yet worked on the knex update.

2020-11-08 19:58 UTC, jhhlim commented on views/profile.hbs
> +<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
will remove

2020-11-08 19:58 UTC, jhhlim commented on routes/profile.js
> +        // .andWhere('collection.has_quantity', '>', 0);
Ok will uncomment this

2020-11-11 00:56 UTC, jhhlim commented
Please review and merge request. Register in Main no longer works.

The register in this branch should work and also adds the is_admin feature (0-5) which is still in progress but at least register will work.

Also has update in progress per individual collectible page

2020-11-11 01:11 UTC, notkimroberts approved these changes

2020-11-11 01:53 UTC, tomki1 approved these changes

2020-11-11 01:53 UTC, merged