feat: trade matches
notkimroberts/collectors-trading-platform pull request #36
Opened 2020-11-08 18:25 UTC by notkimroberts

This PR shows the matches for a user in their profile. 

Note: I was able to do this without the `matches` table so we can probably get rid of it eventually. 

To test: 
- Email: `something2@email.com`
- Password: `Something2`

2020-11-08 21:44 UTC, tomki1 requested changes

2020-11-08 21:44 UTC, tomki1 commented on routes/profile.js
> +        .andWhere('willing_to_trade_quantity', '>', 0)
matches works great but the names of the collectible isn't showing in the matches section. I think we need to join the collectible table to get the name

2020-11-09 02:51 UTC, tomki1 approved these changes
LGTM

2020-11-09 05:11 UTC, jhhlim approved these changes
lgtm

2020-11-09 05:12 UTC, merged