feat: trade match between users + users with collectible
notkimroberts/collectors-trading-platform pull request #41
Opened 2020-11-15 02:20 UTC by notkimroberts

This PR adds two features: 

1. Shows trade matches between users at `/collector/trade/:id`.
2. Shows users with a collectible at `/collectible:id`.

2020-11-15 08:56 UTC, tomki1 approved these changes
i think the right side is working but not the left side of `/collector/trade/:id`

2020-11-15 09:42 UTC, tomki1 requested changes
I think the right side of the page is working but the left side is not working right. 
I'm logged in as something11 (collector_id 4) looking at trade matches with something22 (collector_id 6).  something22(id:6) wants collectible_id 7 which is correct, but something11(id:4) does not have collectible_id 7 for trade, so it shouldn't show up in the left screen. also it says something11 has 2 for trade but he does not per pg admin
![something11 and something22 and collectible 7](https://user-images.githubusercontent.com/38170380/99181374-fc29e300-26e2-11eb-9062-7ea1527cd635.JPG)
![something11 matches with something22](https://user-images.githubusercontent.com/38170380/99181375-fcc27980-26e2-11eb-9535-bd156b02e594.JPG)

2020-11-15 19:17 UTC, jhhlim reviewed
currently testing

2020-11-15 19:28 UTC, jhhlim commented
Are these two left and right reversed? 

Collector ID: 6 , Something22 only has two collectibles in total according to PGAdmin but theres a lot showing up.

![image](https://user-images.githubusercontent.com/31980053/99194669-b5b1a400-2735-11eb-817c-66615cada988.png)


![image](https://user-images.githubusercontent.com/31980053/99194642-8ef36d80-2735-11eb-986f-2ca4c3dda3f0.png)

2020-11-15 19:29 UTC, jhhlim commented
> Are these two left and right reversed?
> 
> Collector ID: 6 , Something22 only has two collectibles in total according to PGAdmin but theres a lot showing up.
> 
> ![image](https://user-images.githubusercontent.com/31980053/99194669-b5b1a400-2735-11eb-817c-66615cada988.png)
> 
> ![image](https://user-images.githubusercontent.com/31980053/99194642-8ef36d80-2735-11eb-986f-2ca4c3dda3f0.png)

What I am seeing is that the left hand side basically shows everything Something11 wants but Something22 does not actually have what Something11 has in stock.

2020-11-15 20:04 UTC, notkimroberts commented
@jhhlim @tomki1 Let me know if you're still seeing issues.

2020-11-15 20:19 UTC, jhhlim approved these changes
lgtm

2020-11-15 20:21 UTC, jhhlim commented
> @jhhlim @tomki1 Let me know if you're still seeing issues.

I tested this with something22 and something12 and it works. I looked at pgadmin to verify the lines and collectible id's to match the willing to trade qty on the trade matches page. Thank you

One last thing that I noted was, we are able to trade with ourselves. I am logged in as something22 and I am seeing something22 in trade matches. 

![image](https://user-images.githubusercontent.com/31980053/99195812-e8ab6600-273c-11eb-818d-41f0873e52b5.png)
![image](https://user-images.githubusercontent.com/31980053/99195823-f8c34580-273c-11eb-9b38-365722869ac5.png)

2020-11-15 20:29 UTC, notkimroberts commented
> > @jhhlim @tomki1 Let me know if you're still seeing issues.
> 
> I tested this with something22 and something12 and it works. I looked at pgadmin to verify the lines and collectible id's to match the willing to trade qty on the trade matches page. Thank you
> 
> One last thing that I noted was, we are able to trade with ourselves. I am logged in as something22 and I am seeing something22 in trade matches.
> 
> ![image](https://user-images.githubusercontent.com/31980053/99195812-e8ab6600-273c-11eb-818d-41f0873e52b5.png)
> ![image](https://user-images.githubusercontent.com/31980053/99195823-f8c34580-273c-11eb-9b38-365722869ac5.png)

I just added a redirect to profile for these cases.

2020-11-16 19:58 UTC, tomki1 approved these changes
LGTM

2020-11-16 19:58 UTC, merged