Insert update
notkimroberts/collectors-trading-platform pull request #45
Opened 2020-11-21 08:11 UTC by jhhlim

insert and update works on all collectibles page. 

1. Enter a quantity and then hit update button
2. Quantities will be updated on the Collectibles page itself
3. Redirected to user's profile page with updated quantities.

2020-11-21 23:57 UTC, notkimroberts approved these changes
LGTM.

2020-11-22 01:00 UTC, tomki1 requested changes
I have some items in my have list, but when I go to the all "collectibles page" it renders the numbers of those haves back to zero. It should render the same values in the profile page

![image](https://user-images.githubusercontent.com/38170380/99891076-e81e3e00-2c1a-11eb-92da-cb1f8653f533.png)
![image](https://user-images.githubusercontent.com/38170380/99891098-0e43de00-2c1b-11eb-83cd-6fcfab6dc723.png)

2020-11-22 17:31 UTC, notkimroberts approved these changes

2020-11-22 20:14 UTC, tomki1 approved these changes

2020-11-22 21:23 UTC, merged