Loginfix
notkimroberts/collectors-trading-platform pull request #47
Opened 2020-11-24 17:45 UTC by jhhlim

fixed login bug on ISSUES tab reported by tomki1

1. Test by submitting / logging in
2. Stay on login page and go to Register page from nav bar
3. Stay on login and click other buttons such as Search collector / collectible

2020-11-25 23:02 UTC, jhhlim commented
Update *11/25/2020
1. Also added PROMO Code section to Register.hbs - Admin account registration validation

2020-11-26 02:58 UTC, notkimroberts approved these changes

2020-11-27 02:02 UTC, jhhlim commented
Added the additional promo code PER admin and functionality
AAA20 - Lego
BBB20 - Funko
CCC20 - Pusheen
RRR20 - Pokemon
DDD20 - Hot Wheel
REG20 - All Admin Account

2020-11-28 00:53 UTC, tomki1 requested changes

2020-11-28 00:53 UTC, tomki1 commented on views/collectible.hbs
> -                        {{#each collectibleNoRow}}
I think line 78 needs to be put back in because I'm getting an error. If you are not working on collectible.hbs I think it shouldn't be part of this pull request

2020-11-28 01:09 UTC, jhhlim commented on views/collectible.hbs
> -                        {{#each collectibleNoRow}}
this is strange. I dont even see these lines in my repo

2020-11-28 01:21 UTC, jhhlim commented
i've put back colletcible.hbs

2020-11-29 09:20 UTC, closed without merging